<script type="text/javascript">
	$(function() {
		$("#compose").validate();
	});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>  Tambah Setting</h1>
	<div class="header_nav_links"><a href="/admin/setting/index">Back to Daftar Setting</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label class="left" for="nama">Nama :</label>
			<input type="text" class="required" id="nama" name="nama" value=""/> <font color="red">*</font>
		</p>
		<p>
			<label class="left" for="nilai">Nilai :</label>
			<input type="text" class="required" id="nilai" name="nilai" value=""/> <font color="red">*</font>
		</p>
	    
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/setting/index" class="UIbutton-small">Kembali</a></p>
	</div>
</form>
<div style="clear:both"></div>