<!--A Design by W3layouts 
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Diplomasi Parlemen Indonesia || BKSAP DPR RI</title>
<link href="<?=$this->url_statik;?>/diparlin/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="<?=$this->url_statik;?>/diparlin/js/jquery.min.js"></script>
<!-- Custom Theme files -->
<!--theme-style-->
<link href="<?=$this->url_statik;?>/diparlin/css/style.css" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Magblog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--fonts-->
<link rel="shortcut icon" type="image/x-icon" href="http://dpr.go.id/favicon.ico" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,700' rel='stylesheet' type='text/css'>
<!--//fonts-->
<script type="text/javascript" src="<?=$this->url_statik;?>/diparlin/js/move-top.js"></script>
<script type="text/javascript" src="<?=$this->url_statik;?>/diparlin/js/easing.js"></script>
				<script type="text/javascript">
					jQuery(document).ready(function($) {
						$(".scroll").click(function(event){		
							event.preventDefault();
							$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
						});
					});
				</script>
<link href="<?=$this->url_statik;?>/diparlin/css/nav.css" rel="stylesheet" type="text/css" media="all"/>
<script src="<?=$this->url_statik;?>/diparlin/js/easyResponsiveTabs.js" type="text/javascript"></script>
		    <script type="text/javascript">
			    $(document).ready(function () {
			        $('#horizontalTab,#horizontalTab1,#horizontalTab2').easyResponsiveTabs({
			            type: 'default', //Types: default, vertical, accordion           
			            width: 'auto', //auto or any width like 600px
			            fit: true   // 100% fit in a container
			        });
			    });
			   </script>


<script src="<?=$this->url_statik;?>/diparlin/js/main.js"></script> <!-- Resource jQuery -->
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  	ga('create', 'UA-48014931-1', 'codyhouse.co');
  	ga('send', 'pageview');

  	jQuery(document).ready(function($){
  		$('.close-carbon-adv').on('click', function(){
  			$('#carbonads-container').hide();
  		});
  	});
</script>		   
</head>
<body>
<!--header-->
<div class="back">
	<img src="<?=$this->url_statik;?>/diparlin/images/back.png" alt="">
</div>	
<div class="container">
<div class="main-top">
	<div class="main">
		<div class="header">
			<div class="header-top">
				<div class="header-in" style="width:100%">
					<div class="logo" style="width:50%">
						<a href="/"><img src="<?=$this->url_statik;?>/diparlin/images/logo1.png" alt="" style=""></a>
					</div>
					<div class="search" style="float:right;width:35%">
						<form id="compose" name="compose" method="post" action="/index/search" enctype="multipart/form-data">
							<input type="text" name="id" value="" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = '';}">
							<input type="submit" value="CARI">
						</form>
					</div>
					<div class="clearfix"> </div>
				</div>
				<? /*
				<div class="header-top-on">
					<ul class="social-in">
						<li><a href="#"><i> </i></a></li>						
						<li><a href="#"><i class="facebook"> </i></a></li>
						<li><a href="#"><i class="tin"> </i></a></li>
					</ul>
				</div>
				*/?>
				<div class="clearfix"> </div>
			</div>
			<!---->
			<div class="header-bottom">
				<div class="navigation">	
				<div>
				  <label class="mobile_menu" for="mobile_menu">
				  <span>Menu</span>
				  </label>
				  <input id="mobile_menu" type="checkbox">
					<ul class="nav">
						<li class="dropdown"><a href="#" class="color5">Beranda <span> </span></a>
						<ul>
						  <li><a href="/index/about/id/1">Pendahuluan</a></li>
						  <li><a href="/index/about/id/2">Landasan Hukum Diplomasi Parlemen Indonesia</a></li>
						  <li><a href="/index/about/id/3">Badan Kerja Sama Antar Parlemen (BKSAP) dan Diplomasi Parlemen Indonesia</a></li>
						  <li><a href="/index/about/id/4">Diplomasi Parlemen Indonesia di Kawasan Regional</a></li>
						  <li><a href="/index/about/id/5">Resolusi</a></li>
						  <li><a href="/index/archives">Arsip</a></li>
						</ul>
						</li>  
						<?
						$indeks = 1;
						$TipeArtikelService = new TipeArtikelService();
						$MenuRows = $TipeArtikelService->getDefaultMenuData();
						foreach($MenuRows as $row)
						{							
							echo '<li><a class="color' . $indeks . '" href="/index/magazine/id/' . $row->id . '">' . $row->tipe_artikel . '</a></li>';

							$indeks++;

							if ($indeks == 6)
								$indeks = 1;
						}
						?>
						<li><a href="/index/contact" class="color6">Kontak</a></li>
						<div class="clearfix"></div>
					</ul>
				</div>			
			</div>
		</div>
	</div>

<?=$this->layout()->content;?>   

	</div>
	<p class="footer-class">Copyright © 2019 Megblog Template by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a><br>
	<a href="http://bdti.dpr.go.id" target="_blank">Bidang Data dan Teknologi Informasi (BDTI)</a></p>
<script type="text/javascript">
						$(document).ready(function() {
							/*
							var defaults = {
					  			containerID: 'toTop', // fading element id
								containerHoverID: 'toTopHover', // fading element hover id
								scrollSpeed: 1200,
								easingType: 'linear' 
					 		};
							*/
							
							$().UItoTop({ easingType: 'easeOutQuart' });
							
						});
					</script>
				<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>


</div>
</body>
</html>