<script type="text/javascript">
var DecimalSeparator = ",";
var ThousandSeparator = ".";
var CurrencyDecimalDigits = 4;

	$(document).ready(function() {
		$("#compose").validate();
		$("#tanggal").datepicker({yearRange:"-100:+1",changeYear:"true",changeMonth:"true",dateFormat:"dd-mm-yy"});
	})
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Tambah Peserta</h1>
	<div class="header_nav_links"><a href="/admin/peserta/index">Back to Daftar Peserta</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label class="left" for="nama">Nama</label>
			<input id="nama" class="event-message" wrap="soft" rows="6" cols="60" name="nama" style="overflow: hidden; display: block;"></input>
		</p>
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/peserta/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>