		<!---->
<div class="content">
	<div class=" content-top">
		<div class="number ">
			<h3 class="page-in"><?=$this->row->judul;?></h3>					
				<p class="page-top"><?=$this->row->konten;?></p>
		<br>
		<div class="simply">
			<? /*<div class="story">
				<h4 class="stories stories-in"><span>Artikel Terkait</span></h4>
			</div>
				<ul class="in-left">
					<?
					foreach($this->RelatedArticleRows as $row)
					{
						echo '<li><a href="/index/single/id/' . $row->id . '">' . $row->judul . ' </a></li>';
					}
					?>
				</ul>
				<div class="clearfix"></div>
			</div>
			
			<div class="comment-top">
				<div class="story">
					<h4 class="stories "><span>comments (3)</span></h4>
				</div>
				<!---->
				<div class="comments-top-top page-top-in">
					<div class="top-comment-left">
						<img class="img-responsive" src="images/co.png" alt="">
					</div>
					<div class="top-comment-right">
						<div class="right-comment">
							<h5>Bitch on the broom</h5>
							<span>05/03/2012 at 13:58</span>
							<div class="clearfix"> </div>
						</div>
						<p>Remaining essentially unchanged. It was popularised in the 1960s with the release of  Letraset sheets containing </p>
						<a href="#" class="reply">Reply</a>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="comments-top-top page-top-in">
					<div class="top-comment-left">
						<img class="img-responsive" src="images/co.png" alt="">
					</div>
					<div class="top-comment-right">
						<div class="right-comment">
							<h5>Bitch on the broom</h5>
							<span>05/03/2012 at 13:58</span>
							<div class="clearfix"> </div>
						</div>
						<p>Remaining essentially unchanged. It was popularised in the 1960s with the release of  Letraset sheets containing </p>
						<a href="#" class="reply">Reply</a>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="comments-top-top page-top-in">
					<div class="top-comment-left">
						<img class="img-responsive" src="images/co.png" alt="">
					</div>
					<div class="top-comment-right">
						<div class="right-comment">
							<h5>Bitch on the broom</h5>
							<span>05/03/2012 at 13:58</span>
							<div class="clearfix"> </div>
						</div>
						<p>Remaining essentially unchanged. It was popularised in the 1960s with the release of  Letraset sheets containing </p>
						<a href="#" class="reply">Reply</a>
					</div>
					<div class="clearfix"> </div>
				</div>
			<!---->
			</div>
			<!---->
			<div class="simply">
				<div class="story">
					<h4 class="stories stories-in"><span>Write comment</span></h4>
				</div>
				<div class="page-bottom">
				<form>
					<div class="name">
						<span class="sit-in">Name:</span>
						<input type="text" value="" >
					</div>
					<div class="name name-at">
						<span class="sit-in">Email:</span>
						<input type="text" value="" >
					</div>
					<div class="name name-on">
						<span class="sit-in">Website:</span>
						<input type="text" value="" >
					</div>
					<div class="name name-in">
						<span class="sit-in">Comment:</span>
						<textarea> </textarea>
					</div>
					<input type="submit" value="Post Comment">
				</form>
				</div>
				<div class="clearfix"> </div>
			</div>*/?>
		</div>
	</div>
	<!---->
		</div>
	</div>
	<i class="line"> </i>
	<i class="line-in"> </i>
	<i class="line-in line-in1"> </i>