<script type="text/javascript">
var DecimalSeparator = ",";
var ThousandSeparator = ".";
var CurrencyDecimalDigits = 4;

	$(document).ready(function() {
		$("#compose").validate();
		$("#tanggal").datepicker({yearRange:"-100:+1",changeYear:"true",changeMonth:"true",dateFormat:"dd-mm-yy"});
	})
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Tambah Silabus Materi</h1>
	<div class="header_nav_links"><a href="/admin/kelasSilabusMateri/index">Back to Daftar Silabus Materi</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label class="left" for="nama_materi">Nama Materi</label>
			<input id="nama_materi" class="event-message" wrap="soft" rows="6" cols="60" name="nama_materi" style="overflow: hidden; display: block;"></input>
		</p>
		<p>
			<label class="left" for="deskripsi_materi">Deskripsi Materi</label>
			<input id="deskripsi_materi" class="event-message" wrap="soft" rows="2" cols="60" name="deskripsi_materi" style="overflow: hidden; display: block;"><?= $this->deskripsi_materi ?></input>
		</p>
		<p>
			<label class="left" for="gambar_materi_uri">Gambar Silabus Materi</label> 
			<input type="file" accept="image/*" id="file_image" name="file_image">
		</p>
		<p>
			<label class="left" for="document_materi_uri">File Silabus Materi</label> 
			<input type="file" accept="document/*" id="file_pdf" name="file_pdf">
		</p>
		
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/mentor/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>