<script type="text/javascript">
	$(document).ready(function() {
		$("#compose").validate();
	})
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>Edit Mentor</h1>
	<div class="header_nav_links"><a href="/admin/kelas-silabus-materi/index">Back to Daftar Kelas Silabus Materi</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
<div class="tabular">
		<p>
			<label class="left" for="nama_materi">Nama Materi</label>
			<textarea id="nama_materi" class="event-message" wrap="soft" rows="2" cols="60" name="nama_materi" style="overflow: hidden; display: block;"><?= $this->row->nama_materi; ?></textarea>
		</p>
		<p>
			<label class="left" for="deskripsi_materi">Deskripsi Materi</label>
			<textarea id="deskripsi_materi" class="event-message" wrap="soft" rows="2" cols="60" name="deskripsi_materi" style="overflow: hidden; display: block;"><?= $this->row->deskripsi_materi ?></textarea>
		</p>
		<p>
			<label class="left" for="gambar_materi_uri">Gambar Silabus Materi</label> 
			<?
			if ($this->row->gambar_materi_uri != '') {
				echo '<img src="https://berkas.dpr.go.id/mooc/gambarmateri/' . $this->row->gambar_materi_uri . '" height="200" />';
				echo '<a href="/admin/kelas-silabus-materi/delete-files/id/' . $this->row->id . '  ">Hapus</a>';
				echo '<input type="hidden" id="file_image" autocomplete="disable" name="file_image" value="'.$this->row->gambar_materi_uri.'"/>';
			} else {
				echo '<input type="file" accept="image/*" id="file_image" autocomplete="disable" name="file_image"/>';
			}
			?>
		</P>
		<p>
			<label class="left" for="document_materi_uri">File Silabus Materi</label> 
			<?
			if ($this->row->document_materi_uri != '') {
				echo '<img src="https://berkas.dpr.go.id/mooc/filemateri/' . $this->row->document_materi_uri . '" height="200" />';
				echo '<a href="/admin/kelas-silabus-materi/delete-files/id/' . $this->row->id . '  ">Hapus</a>';
				echo '<input type="hidden" id="file_pdf" autocomplete="disable" name="file_pdf" value="'.$this->row->document_materi_uri.'"/>';
			} else {
				echo '<input type="file" accept="document/*" id="file_pdf" autocomplete="disable" name="file_pdf"/>';
			}
			?>
		</P>

		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class="" /></label><a href="/admin/kelas-silabus-materi/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>