<script type="text/javascript">
	$(function() {
		$("#compose").validate();
	});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>  Tambah Kontak</h1>
	<div class="header_nav_links"><a href="/admin/kontak/index">Back to Daftar Kontak</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label class="left" for="nama">Nama :</label>
			<input type="text" class="required" id="nama" name="nama" value=""/> <font color="red">*</font>
		</p>
		<p>
			<label class="left" for="email">Email :</label>
			<input type="text" class="required" id="email" name="email" value=""/> <font color="red">*</font>
		</p>
		<p>
			<label class="left" for="judul">Judul :</label>
			<input type="text" class="required" id="judul" name="judul" value=""/> <font color="red">*</font>
		</p>
		<p>
			<label class="left" for="pesan">Pesan :</label>
			<textarea class="required" id="pesan" name="pesan" wrap="soft" rows="6" cols="60"></textarea> <font color="red">*</font>
		</p>
	    
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/kontak/index" class="UIbutton-small">Kembali</a></p>
	</div>
</form>
<div style="clear:both"></div>